# 自学NLP
## 2021.10.1 Leakey
# 一、基本元素操作：创建张量

In [6]:
print ('hello')

hello


### 1.初始化，引入torch

In [34]:
from __future__ import print_function
import torch

### 2.生成0-1分布随机数

In [8]:
x = torch.rand(4,6)
print (x)

tensor([[0.4760, 0.3274, 0.7162, 0.2444, 0.3315, 0.8795],
        [0.1017, 0.4411, 0.5175, 0.4325, 0.2167, 0.1982],
        [0.0230, 0.5669, 0.8069, 0.9705, 0.4764, 0.9564],
        [0.6499, 0.0636, 0.0584, 0.6248, 0.3388, 0.5460]])


### 3.生成空矩阵，数据来源于内存空间，无实际意义

In [9]:
y = torch.empty(9,6)
print (y)

tensor([[4.0047e-11, 6.4465e-10, 6.2983e-10, 4.3199e-05, 3.1458e-12, 7.9309e+34],
        [6.0022e+31, 4.2964e+24, 7.3162e+28, 1.6992e-07, 1.1692e-19, 1.5637e-01],
        [2.9560e+21, 8.1997e-10, 5.0782e+31, 4.2964e+24, 1.1632e+33, 1.2734e-14],
        [1.8106e+22, 2.4457e-15, 1.3556e-19, 1.8567e-01, 7.2053e+22, 4.7428e+30],
        [1.3292e-14, 2.6339e+20, 1.1703e-19, 5.0746e+31, 7.5338e+28, 6.1687e+16],
        [6.4890e-07, 2.5609e-12, 4.0046e-11, 6.5635e-07, 1.1704e-19, 1.3563e-19],
        [1.3563e-19, 4.5071e+16, 4.0556e-08, 2.5038e-12, 4.0058e-11, 1.7156e-07],
        [1.4600e-19, 1.8617e+25, 2.6284e-15, 2.6339e+20, 3.7123e-14, 1.3556e-19],
        [1.8567e-01, 7.2053e+22, 4.7428e+30, 1.3292e-14, 2.6339e+20, 1.1819e+22]])


### 4.创建数据类型为long的0阵（注意数据局类型的写法）

In [10]:
 z = torch.zeros(5,3,dtype=torch.long)
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### 5.直接用数据创建张量(封装的写法）

In [11]:
array1 = torch.tensor([3.84,1.381])
print(array1)

tensor([3.8400, 1.3810])


### 6.通过已有的张量创建相同尺寸的新张量

In [12]:
a2 = x.new_ones(6,6, dtype=torch.double)
print(a2)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=torch.float64)


注意x.new_ones写法,输出"1."表示浮点数

In [13]:
a3 = torch.randn_like(a2, dtype=torch.float)
print(a3)

tensor([[-1.1163,  0.1088,  0.4783,  0.9531, -0.6290,  0.1371],
        [ 0.1717, -0.9238,  0.5265,  0.2374, -0.0634,  1.5140],
        [ 1.0911, -0.4846,  0.2458,  0.3590,  1.4968,  1.1096],
        [-0.6876, -1.9983,  0.0220, -1.1601, -0.7821, -0.6985],
        [ 0.4961,  1.0327, -0.1889, -0.4654, -0.9942,  2.0424],
        [-1.4605,  0.3609,  0.7356,  1.2354,  1.2389, -1.3702]])


采用.size得到张量形状（对元组tuple进行操作）

In [14]:
print(a2.size())
print(a3.size())

torch.Size([6, 6])
torch.Size([6, 6])


# 二、基本运算操作

### 1.加法
#### 方法一：直接相加并输出

In [15]:
a4=torch.rand(4,6)
print(a4)
print(x+a4)

tensor([[0.1212, 0.7274, 0.3749, 0.3305, 0.1213, 0.3909],
        [0.1865, 0.1920, 0.2513, 0.4494, 0.4682, 0.5707],
        [0.1454, 0.1185, 0.9734, 0.1577, 0.5881, 0.0625],
        [0.1865, 0.3332, 0.4500, 0.7370, 0.9112, 0.9969]])
tensor([[0.5971, 1.0548, 1.0911, 0.5750, 0.4528, 1.2703],
        [0.2882, 0.6331, 0.7688, 0.8819, 0.6850, 0.7690],
        [0.1684, 0.6854, 1.7802, 1.1283, 1.0645, 1.0189],
        [0.8364, 0.3968, 0.5083, 1.3618, 1.2501, 1.5429]])


#### 方法二：torch.add

In [16]:
print(torch.add(x,a4))

tensor([[0.5971, 1.0548, 1.0911, 0.5750, 0.4528, 1.2703],
        [0.2882, 0.6331, 0.7688, 0.8819, 0.6850, 0.7690],
        [0.1684, 0.6854, 1.7802, 1.1283, 1.0645, 1.0189],
        [0.8364, 0.3968, 0.5083, 1.3618, 1.2501, 1.5429]])


#### 方法三：创建空张量，用torch.add利用out输出

In [17]:
result = torch.empty(4,6)
torch.add(x,a4,out=result)
print(result)

tensor([[0.5971, 1.0548, 1.0911, 0.5750, 0.4528, 1.2703],
        [0.2882, 0.6331, 0.7688, 0.8819, 0.6850, 0.7690],
        [0.1684, 0.6854, 1.7802, 1.1283, 1.0645, 1.0189],
        [0.8364, 0.3968, 0.5083, 1.3618, 1.2501, 1.5429]])


#### 方法四：in-place原地置换（in-place类操作记得写下划线，copy，sub等同理）

In [18]:
a4.add_(x)
print(a4)

tensor([[0.5971, 1.0548, 1.0911, 0.5750, 0.4528, 1.2703],
        [0.2882, 0.6331, 0.7688, 0.8819, 0.6850, 0.7690],
        [0.1684, 0.6854, 1.7802, 1.1283, 1.0645, 1.0189],
        [0.8364, 0.3968, 0.5083, 1.3618, 1.2501, 1.5429]])


相当于将x中元素直接加到a4当中，a4值直接发生改变

### 2.用类似Numpy的方式对张量进行切片操作

In [19]:
print(x[:,1])

tensor([0.3274, 0.4411, 0.5669, 0.0636])


In [20]:
print(a4[:,:2])

tensor([[0.5971, 1.0548],
        [0.2882, 0.6331],
        [0.1684, 0.6854],
        [0.8364, 0.3968]])


### 3.改变张量的形状

In [21]:
a6 = torch.randn(4,4)

y = a6.view(16)
#view()中只能用可整除的行数/列数进行赋值

z = a6.view(-1,8)
# -1表示自动匹配

print(x.size(),y.size(),z.size())

torch.Size([4, 6]) torch.Size([16]) torch.Size([2, 8])


如果张量中只有一个元素，可以用.item()直接取出，作为一个python number

In [22]:
a7=torch.randn(1)
print(a7)
print(a7.item())

tensor([2.4618])
2.4618215560913086


# 三、关于Torch Tensor和Numpy Array之间的互相转换

### 1.Torch Tensor和Numpy Array共享底层空间，可互相转换

In [23]:
a8=torch.ones(5)
print(a8)

tensor([1., 1., 1., 1., 1.])


In [24]:
b = a8.numpy()
print(b)

[1. 1. 1. 1. 1.]


对其中一个做加法，另一个也会改变（注意： a8 与 b 底层存储空间共享）

In [25]:
a8.add_(1)
print(a8)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 2.将Numpy Array转换为Torch Tensor（底层依然共享）

In [26]:
import numpy as np
a9 = np.ones(5)
b = torch.from_numpy(a9)
np.add(a9,1, out=a9)
print(a9)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


除了CharTensor之外，剩下的都可以转转

### 3.关于Cuda Tensor: Tensors可以用.to()方法将其移动到任意设备上

In [2]:
#if torch.cuda.is_available():

#    devil = torch.device("cuda")

#y= torch.ones_like(x,device = devil)